### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by akapei** [sinelaw/xml-to-json#6]
I have followed the instructions but when I went to run the command in the Terminal is says:
"-bash: xml-to-json: command not found".

Any help would be appreciated because this tools would be awesome!

**Comment by sinelaw** [comment]
How did you build? Did you run cabal install?

**Comment by sinelaw** [comment]
Also, make sure your PATH includes ~/.cabal/bin

**Comment by akapei** [comment]
Yep ran cabal install. 

Can you explain the second comment? What do you mean by PATH includes ~/.cabal/bin?

**Comment by sinelaw** [comment]
See the [cabal install wiki page](https://wiki.haskell.org/Cabal-Install#Installation) for more.
What I meant was, does your [PATH environment variable](https://en.wikipedia.org/wiki/PATH_%28variable%29) include the location of cabal's output, which is normally in linux is under your home directory in `.cabal/bin`?

**Comment by akapei** [comment]
No it doesn't appear to be there.

**Comment by sinelaw** [comment]
To make this easier - run

    cabal clean
    cabal install

Then paste the output somewhere where I can take a look.

**Comment by akapei** [comment]
This is what I get when I ran cabal clean:
cabal: No cabal file found.
Please create a package description file <pkgname>.cabal

**Comment by sinelaw** [comment]
Sorry about that - run `cabal install` alone and paste the output, please

**Comment by akapei** [comment]
Here is the output for cabal install: 
Resolving dependencies...
In order, the following will be installed:
xml-to-json-1.0.1 (reinstall) changes: directory-1.2.1.0 added,
process-1.2.0.0 added
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring xml-to-json-1.0.1...
Building xml-to-json-1.0.1...
Installed xml-to-json-1.0.1
Updating documentation index /Users/Max/Library/Haskell/share/doc/index.html

**Comment by sinelaw** [comment]
What platform / OS are you using?

**Comment by akapei** [comment]
Mac OS X Yosemite

**Comment by sinelaw** [comment]
First, let's make sure xml-to-json is installed where I think it is.

Try running it like this:

    /Users/Max/Library/Haskell/bin/xml-to-json

Or like this:

    ~/Library/Haskell/bin/xml-to-json

That should work (you can use `--help` to see command line options).

Assuming it **does** work, [this wiki page](https://wiki.haskell.org/Mac_OS_X_Common_Installation_Paths) may help you. One thing it says is:

> For user installs, since ~/bin is not on the PATH by default on Mac OS X and may not exist, binaries are symlink'd into:

    ~/Library/Haskell/bin

So try to add "/Users/Max/Library/Haskell/bin" to your PATH environment variable. Google "os x add path to environment variable" or try [this stackoverflow answer](https://stackoverflow.com/questions/7501678/set-environment-variables-on-mac-os-x-lion).

**Comment by akapei** [comment]
Yep that did it. It's working! Thank you so much!!!!
