### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ZuodiDavid** [sinelaw/xml-to-json#8]
Tried to turn a xml file downloaded from wikipedia https://dumps.wikimedia.org/enwiki/latest/ , but failed. I tried .js file, .json file, with or without -a option, it was either 'Killed' or 'Segmentation fault, core dumped'.

**Comment by sinelaw** [comment]
Those files are big. Can you try with [xml-to-json-fast](https://github.com/sinelaw/xml-to-json-fast)? It's much better at handling big files (at the cost of less features)

**Comment by sinelaw** [comment]
I've checked with [xml-to-json-fast](https://github.com/sinelaw/xml-to-json-fast) on one of the files (this [165MB one](https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-abstract11.xml)) and it worked.

So again, xml-to-json doesn't support large files properly, please try  [xml-to-json-fast](https://github.com/sinelaw/xml-to-json-fast).

Thanks for reporting this!
